const express = require('express');
const router = express.Router();
const axios = require('axios');

// This is a simplified alternative chatbot implementation that uses a different AI provider
// or falls back to rule-based responses when AI is unavailable

// Climate-related predefined responses
const climateResponses = {
    "weather": "The current weather patterns show significant variations from historical averages, which is consistent with climate change predictions. Local weather conditions can be checked using our weather section.",
    
    "climate change": "Climate change refers to long-term shifts in temperatures and weather patterns. Human activities, particularly burning fossil fuels, are the main driver of current climate change. Effects include rising temperatures, changing precipitation patterns, and more extreme weather events.",
    
    "renewable energy": "Renewable energy sources like solar, wind, and hydroelectric power are crucial for reducing carbon emissions. The cost of renewable technologies has decreased significantly in recent years, making them increasingly competitive with fossil fuels.",
    
    "sustainability": "Sustainability involves meeting our present needs without compromising future generations. Key practices include reducing waste, conserving energy and water, using renewable resources, and supporting eco-friendly businesses.",
    
    "carbon footprint": "Your carbon footprint is the total amount of greenhouse gases generated by your actions. You can reduce it by using public transportation, eating less meat, reducing energy consumption, and choosing products with minimal packaging.",
    
    "recycling": "Recycling helps reduce waste sent to landfills, conserves natural resources, and reduces pollution. Materials commonly recycled include paper, plastic, glass, and aluminum.",
    
    "global warming": "Global warming is the long-term heating of Earth's climate system observed since the pre-industrial period due to human activities, primarily fossil fuel burning. The average global temperature has increased by about 1.1°C since the pre-industrial era.",
    
    "sea level rise": "Sea levels are rising due to thermal expansion of warming ocean water and melting ice sheets and glaciers. This threatens coastal communities, infrastructure, and ecosystems worldwide.",
    
    "extreme weather": "Climate change is increasing the frequency and intensity of extreme weather events like hurricanes, floods, droughts, and heatwaves. These events cause significant damage to communities and ecosystems.",
    
    "deforestation": "Deforestation contributes to climate change by reducing carbon storage, disrupting water cycles, and destroying biodiversity. Sustainable forest management and reforestation efforts are essential for mitigating these impacts."
};

// Function to get the most relevant predefined response
function getRelevantResponse(message) {
    const lowerMessage = message.toLowerCase();
    
    // Check for exact matches first
    for (const [key, response] of Object.entries(climateResponses)) {
        if (lowerMessage.includes(key)) {
            return response;
        }
    }
    
    // If no exact match, return a general response
    return `Thank you for your question about climate awareness. Our portal provides information on various climate topics including weather patterns, sustainability practices, renewable energy, and environmental conservation. Please explore our articles section for detailed information on these topics.`;
}

// Function to generate a more dynamic response based on the query
function generateDynamicResponse(message) {
    const lowerMessage = message.toLowerCase();
    
    // Weather-related queries
    if (lowerMessage.includes('weather') || lowerMessage.includes('temperature') || lowerMessage.includes('forecast')) {
        return `**Current Climate Patterns**

Weather and climate are distinct but related concepts. Weather refers to short-term atmospheric conditions, while climate describes long-term patterns.

Our climate data shows significant changes in recent decades:
• Global temperatures have risen approximately 1.1°C since pre-industrial times
• Weather patterns are becoming more unpredictable and extreme
• Seasonal shifts are affecting agriculture and ecosystems

For specific local weather information, please check our weather section which provides real-time data and forecasts.`;
    }
    
    // Sustainability queries
    if (lowerMessage.includes('sustainable') || lowerMessage.includes('green') || lowerMessage.includes('eco-friendly')) {
        return `**Sustainability Practices**

Sustainability is about meeting our present needs without compromising future generations. Here are some key practices:

• **Energy Conservation**: Reduce consumption, use energy-efficient appliances
• **Waste Reduction**: Recycle, compost, avoid single-use items
• **Water Conservation**: Fix leaks, install water-efficient fixtures
• **Sustainable Transportation**: Walk, bike, use public transit, or electric vehicles
• **Eco-Friendly Shopping**: Buy local, choose products with minimal packaging

Small changes in daily habits can collectively make a significant impact on our environment.`;
    }
    
    // Climate change queries
    if (lowerMessage.includes('climate change') || lowerMessage.includes('global warming')) {
        return `**Climate Change Overview**

Climate change refers to long-term shifts in temperatures and weather patterns. Key points:

• **Causes**: Primarily human activities, especially burning fossil fuels
• **Effects**: Rising temperatures, changing precipitation patterns, extreme weather events
• **Current Status**: Global temperature has risen ~1.1°C since pre-industrial times
• **Projections**: Without action, temperatures could rise 2-4°C by 2100
• **Solutions**: Renewable energy, energy efficiency, sustainable practices

The scientific consensus is clear that climate change is real, caused by humans, and requires urgent action.`;
    }
    
    // Renewable energy queries
    if (lowerMessage.includes('renewable') || lowerMessage.includes('solar') || lowerMessage.includes('wind') || lowerMessage.includes('clean energy')) {
        return `**Renewable Energy**

Renewable energy comes from naturally replenishing sources with minimal environmental impact:

• **Solar**: Photovoltaic panels convert sunlight directly to electricity
• **Wind**: Turbines harness wind energy to generate power
• **Hydroelectric**: Uses flowing water to produce electricity
• **Geothermal**: Utilizes heat from within the Earth
• **Biomass**: Organic material converted to fuel

Renewable energy is becoming increasingly cost-competitive with fossil fuels and is essential for reducing carbon emissions.`;
    }
    
    // Default response for other queries
    return getRelevantResponse(message);
}

// Route handler for chatbot requests
router.post('/ask', async (req, res) => {
    const { message } = req.body;
    
    if (!message || message.trim().length === 0) {
        return res.status(400).json({
            error: 'Message is required',
            reply: 'Please provide a message for me to respond to. I\'m here to help with climate and environmental questions!'
        });
    }
    
    try {
        console.log(`[Alternative Chatbot] Received message: "${message}"`);
        
        // Generate a response based on the message
        const reply = generateDynamicResponse(message);
        
        // Add a small delay to simulate processing time
        await new Promise(resolve => setTimeout(resolve, 500));
        
        console.log(`[Alternative Chatbot] Sending reply: "${reply.substring(0, 100)}..."`);
        
        res.json({
            reply,
            timestamp: new Date().toISOString()
        });
        
    } catch (error) {
        console.error('[Alternative Chatbot] Error:', error);
        
        res.status(500).json({
            reply: `I apologize, but I'm experiencing technical difficulties right now. Please try again in a moment, or explore our climate articles section for information.`,
            error: true,
            timestamp: new Date().toISOString()
        });
    }
});

module.exports = router;